### PR TITLE
Adding Jake Archibald's transcript

### PR DESCRIPTION
**Pull request by gnbezerra**
Jake Archibald's transcript for the BrazilJS 2016 talk. Has 4 [INAUDIBLE] tags in parts I just couldn't understand. Still needs the final video cut to be able to add timecodes.

### CODE REVIEW

**Comment by felipenmoura** [comment]
Very cool, thank you @gbezerras :)
For us to use it as `.srt`, we  need the timestamps.
You think you can do that, or could someone else try and do it?

**Comment by gnbezerra** [comment]
Well, I can do that, but will it be added to the original 10+ hours video of the live transmission?

I didn't do it yet because I don't know if there will be another version of the video (maybe in HD, maybe with separated videos for each talk) or if the recorded live transmission in BrazilJS's channel is the final version. The timestamps could change if it's not the final version.

**Comment by felipenmoura** [comment]
yep, you are right.
It will **not**.
It will be added to the separated video, from Jake only, and yes, it would change the timings.
So, stand by for new publications of videos :p 
Thanks for pointing this out.
I believe the videos will be public in about a week.

**Comment by jaydson** [comment]
Hey!
We enabled the community contributions on YouTube.
http://www.youtube.com/timedtext_video?v=k6P9ndFNarg&ref=share

@gbezerras can you try it?

**Pull request merged**
